### ISSUE TITLE
[feature request] Zed Editor Support

### ISSUE THREAD

**Issue by emnul** [Jannchie/codetime-web-v3#10]
Hi I enjoy using the [Zed](https://zed.dev/) editor for my day to day development. Would it be okay if I made a CodeTime plugin for the Zed editor? Not sure if that's possible as it would likely require some API keys / secrets to send data to your servers. If you're interested in collaborating together to make this a thing, please let me know and I would be happy to help!

**Comment by Jannchie** [comment]
Thank you for your interest. However, I don’t know anything about Zed, so it’s difficult for me to start developing for it. Fortunately, we have intended to keep the plugin design relatively simple. Perhaps you can refer to the implementation at https://github.com/datreks/codetime-vscode to create a third-party plugin.

**Comment by emnul** [comment]
Dang, unfortunately it's not possible to port CodeTime to Zed at this time. Based on what I see in https://github.com/datreks/codetime-vscode Zed would need to be able to start a background process that runs the plugin. For now, Zed only supports extensions that add support for a new language, theme, or grammar.
