### ISSUE TITLE
CodeTime JetBrains Plugin Update Needed

### ISSUE THREAD

**Issue by soxft** [Jannchie/codetime-web-v3#11]
When using the CodeTime JetBrains plugin, it keeps prompting 'Invalid token' even though the token is correct. However, the same token works fine in VSCode. 

The last update for the CodeTime JetBrains plugin was version 0.0.9, which seems to be quite a while ago. 

I have noticed that the API interface seems to have changed here:

https://github.com/datreks/codetime-jetbrains/commit/28abaf0293f7d8ed55fdb4949055d858a7db0df7

And  certificate of the old domain  seems to be expired.

here is the log of Jetbrain IDE

```
2024-09-13 16:44:49,695 [1405564]   WARN - CodeTime - check token failed:PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	com.github.kittinunf.fuel.core.FuelError$Companion.wrap(FuelError.kt:84)
```

**Comment by soxft** [comment]
https://github.com/datreks/codetime-jetbrains/issues/12

**Comment by Jannchie** [comment]
Indeed, the person responsible for creating the JetBrains plugin is really too busy; perhaps I should take over this part of the development.

**Comment by soxft** [comment]
Thank you very much for this amazing open-source project

It has been a great help in understanding my daily development.

**Comment by longmaobure** [comment]
It's 2025, and the version in idea is still 0.0.9. What are you doing?

**Comment by Jannchie** [comment]
> It's 2025, and the version in idea is still 0.0.9. What are you doing?

plz use this one...

https://plugins.jetbrains.com/plugin/25617-codetime/edit
