### ISSUE TITLE
Website or server stayed down for two days.

### ISSUE THREAD

**Issue by Ansh-Rathod** [Jannchie/codetime-web-v3#12]
hi, the website and server stayed down for two days, and not sure it will stay like this but I guess I lost some hours. i visit website and code everyday so please make it work again.

**Comment by ianjamesburke** [comment]
Still seems to be down?

**Comment by Jannchie** [comment]
The cloud service was down and I was on vacation. I'm currently working on restoring from backup...

**Comment by Jannchie** [comment]
I have made every effort to recover the data and have migrated the entire service to a more stable cloud service platform. 

Access speed should be significantly improved now. However, I regret to inform you that data from the past three days was not properly recorded. 

I sincerely apologize for any inconvenience this may have caused.

**Comment by Ansh-Rathod** [comment]
Thank you for restoring it.
