### ISSUE TITLE
[Feature Request] Multi folder support

### ISSUE THREAD

**Issue by zhuozhiyongde** [Jannchie/codetime-web-v3#2]
Currently, I can only select one folder element to view the time and language information. However, I have worked on a project that has multiple levels of folders, such as:

```text
Introduction-To-Computer-System-2023Fall-PKU/
├── 01-Data-Lab
├── 02-Bomb-Lab
├── 03-Attack-Lab
├── 04-Arch-Lab
├── 05-Cache-Lab
├── 06-Tsh-Lab
├── 07-Malloc-Lab
├── 08-Proxy-Lab
├── LICENSE
├── README.md
├── Treehole
├── tempCodeRunnerFile.py
├── 回课
├── 期中考试复习细节.md
├── 期末考试复习细节.md
└── 期末往年题勘误、详解.md
```

All of the lab folders have been my work folders. Additionally, I have spent a significant amount of time working in the `Introduction-To-Computer-System-2023Fall-PKU/` folder. Therefore, it would be helpful if CodeTime could support selecting multiple folders and summarizing all of their data.

I think this feature may need to write a new page like "Analysis". Thanks for you patient to considering this suggestion.

**Comment by Jannchie** [comment]
We are mindful of this need. In the coming months, we will create a detail page for each workspace. This will include the programming time of individual folders and even files.

**Comment by zhuozhiyongde** [comment]
@Jannchie 似乎现有检索是大小写敏感的，能改成不敏感的吗

**Comment by Jannchie** [comment]
> 似乎现有检索是大小写敏感的，能改成不敏感的吗

emm，我稍微改了下 filter，现在应该没问题了。
