### ISSUE TITLE
[Feature Request] Comparison with other code time statistics tools

### ISSUE THREAD

**Issue by siaikin** [Jannchie/codetime-web-v3#4]
I've been using wakapi（Wakatime's open-source server version） to collect data for over a year, but I've only looked at the data a handful of times. Part of the reason is that his data charts are boring and tedious.

I've seen cool charts from codetime here https://x.com/__codetime/status/1749742330427629935?s=20. But I can only see simple pages on your official website.

I believe your charts are your absolute strength and you should put them on your official page instead of hiding them in your tweets.

One more thing, maybe you could add a comparison with other tools like wakatime on the official page to show your advantages?

**Comment by Jannchie** [comment]
Thanks for reaching out with your feedback. We appreciate your interest in Codetime. We're constantly working to improve our platform and make our data visualizations more engaging and informative for users like you.

Regarding the comparison with other tools like Wakatime, we believe it's valuable for users to understand the unique features and advantages of Codetime.  But Wakatime is a great work, in addition to the official dashboard, there are a lot of interesting dashboards developed by many users around to be able to show up on the github homepage, and we are still catching up with it. 

We've made some efforts by introducing some charts on the homepage. Originally, we planned to provide users with a complete demo dashboard using dummy data, but the development workload is quite substantial. We'll continue to work on completing it.

Thank you again for bringing this to our attention, and please feel free to reach out if you have any further suggestions or feedback. We're committed to providing the best possible experience for our users.

**Comment by siaikin** [comment]
Thanks for the quick reply and explaining why. I will do so.
