### ISSUE TITLE
no link to extension on your website

### ISSUE THREAD

**Issue by distbit0** [Jannchie/codetime-web-v3#6]
Hi I just came across this project. I found it suprisingly difficult to locate your vscode extension, as it was not linked to on your website and is also not in the vscode extension results if one searches for "code time" (with the space). Confusingly, this returns another extension called "code time", which is non-functional. I was only able to find it after searching for "codetime".

Perhaps there is a link on your site to the extension. However I did not see it in the first several minutes of browsing your website, so I think it should be made more prominent.

thx

**Comment by Jannchie** [comment]
Thank you for your feedback! I appreciate your comments and have taken them into consideration. I have added more prominent prompts and links to the token section and at the bottom of the page to help new users easily find our extension.
